from pathlib import Path
import re
from pypdf import PdfReader
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION

pdf_path = Path("C:/Users/Arindam Samadder/Downloads/Computer_Networks_500_Placement_Questions-1.pdf")
reader = PdfReader(str(pdf_path))
text = "\n".join(page.extract_text() or "" for page in reader.pages)

questions = {}
for m in re.finditer(r"(?m)^\s*(\d{1,3})\.\s+(.+?)\s*$", text):
    n = int(m.group(1))
    q = m.group(2).strip()
    if 1 <= n <= 500 and n not in questions:
        questions[n] = q

# Concise, intermediate-level answers. Each answer is kept to roughly two readable lines.
answers = {
1:"A computer network connects devices so they can exchange data and share resources. It supports communication, Internet access, file sharing, and distributed applications.",
2:"The main goals are reliable communication, resource sharing, scalability, performance, security, and availability. A good network should move data efficiently between the right endpoints.",
3:"A host is a device with an IP address; a node is any connected device. An endpoint is a communication end, while a network device forwards or controls traffic.",
4:"A protocol is a set of agreed rules for communication. Protocols are necessary so different devices and software can understand the same messages and behavior.",
5:"Data is the general information being transmitted; a segment is a Transport-layer unit and a packet is a Network-layer unit. A frame is the Data Link-layer unit.",
6:"Bandwidth is maximum link capacity, throughput is actual transfer rate, and goodput is useful application data rate. Latency is the time needed for data to travel.",
7:"Jitter is variation in packet delay over time. It matters for voice and video because uneven arrival times can cause pauses, distortion, or buffering.",
8:"Packet loss means packets never reach their destination. Congestion, weak wireless signals, faulty hardware, interference, overloaded devices, and configuration errors are common causes.",
9:"Unicast is one-to-one, broadcast is one-to-all on a local broadcast domain, and multicast is one-to-many subscribers. Anycast sends traffic to one suitable member of a group.",
10:"Topology describes how devices are arranged. Bus shares one backbone, star uses a central device, ring forms a loop, mesh adds many links, and hybrid combines designs.",
11:"LAN covers a small local area; MAN covers a city; WAN covers large geographic areas. PAN is personal-range networking, while WLAN is a wireless LAN.",
12:"Client-server networks use dedicated servers to provide services to clients. Peer-to-peer networks let devices communicate more directly and share roles without a central server.",
13:"Packet switching divides data into packets that share network links with other traffic. It is efficient because links do not need a dedicated circuit for every connection.",
14:"Circuit switching reserves a dedicated path for a session, giving predictable capacity. Packet switching shares links dynamically, using bandwidth more efficiently but with variable delay.",
15:"Multiplexing lets multiple signals share one physical link. TDM separates users by time slots, while FDM separates them by frequency bands.",
16:"Simplex allows one-way communication, half-duplex allows both directions but not simultaneously, and full-duplex allows both directions at the same time.",
17:"A collision domain is a network area where simultaneous transmissions can interfere. Modern switches normally create a separate collision domain for each active port.",
18:"A broadcast domain is the set of devices that receive a Layer-2 broadcast. Routers normally separate broadcast domains, while ordinary switches forward broadcasts within a VLAN.",
19:"Encapsulation adds headers and sometimes trailers as data moves down the stack. Decapsulation removes those headers as the receiver moves back up the stack.",
20:"Layering divides networking into manageable responsibilities. It makes protocols easier to design, troubleshoot, replace, and understand without changing the entire system.",
21:"The seven OSI layers are Physical, Data Link, Network, Transport, Session, Presentation, and Application, from Layer 1 to Layer 7.",
22:"The Physical layer sends raw bits as electrical, optical, or radio signals. It defines things such as media, connectors, signaling, and transmission characteristics.",
23:"The Data Link layer handles frames, MAC addressing, local delivery, and error detection. Ethernet and Wi-Fi are major examples associated with this layer.",
24:"The Network layer provides logical addressing and routing between networks. IP is the main example, while routers make forwarding decisions using Layer-3 information.",
25:"The Transport layer provides process-to-process communication using ports. TCP adds reliability and flow/congestion control, while UDP provides a simpler datagram service.",
26:"The Session layer conceptually manages communication sessions, while Presentation handles data representation, translation, compression, and encryption. Modern Internet stacks often combine these functions.",
27:"The Application layer provides network services directly to applications. HTTP, DNS, SMTP, and many other application protocols operate at this level.",
28:"Typical PDUs are bits at Physical, frames at Data Link, packets at Network, and segments or datagrams at Transport. Higher layers usually refer to data or messages.",
29:"MAC addresses are primarily used at the Data Link layer for local Ethernet or Wi-Fi delivery. Switches use destination MAC addresses to forward frames.",
30:"The Network layer handles logical addressing and routing. IPv4 and IPv6 addresses identify networks and hosts across interconnected networks.",
31:"The Transport layer provides end-to-end process communication. Ports identify applications, while protocols such as TCP and UDP carry data between those processes.",
32:"Framing is mainly a Data Link-layer responsibility. The layer places network-layer packets into frames with local addressing and error-detection information.",
33:"Encryption and data representation are conceptually associated with the Presentation layer. In real Internet systems, these functions may be implemented across several layers.",
34:"HTTP is Application, TCP is Transport, IP is Network, Ethernet is Data Link, and physical cables/radio are Physical. This mapping is conceptual, not absolute.",
35:"OSI gives engineers a common language for discussing network functions and failures. It remains useful even though real protocols often span or cross its layer boundaries.",
36:"A hub works at Physical, a switch mainly at Data Link, and a router at Network. A gateway is broader and can translate between different protocols or systems.",
37:"A service describes what a layer offers, an interface describes how another layer accesses it, and a protocol defines how peer entities communicate to provide that service.",
38:"Each OSI layer logically communicates with the corresponding layer on the remote device. In reality, data moves down the local stack and up the remote stack.",
39:"A web request moves from Application data through Transport, Network, Data Link, and Physical transmission; the receiver reverses this process during decapsulation.",
40:"Protocols often span multiple OSI layers or are implemented differently in practice. OSI is a conceptual guide, so forcing every protocol into exactly one layer can mislead.",
41:"The common four-layer TCP/IP model is Application, Transport, Internet, and Network Access/Link. Some texts use a five-layer version by separating Physical.",
42:"OSI has seven conceptual layers, while TCP/IP uses fewer practical layers. TCP/IP is closely tied to the actual Internet protocol suite and is therefore more implementation-oriented.",
43:"OSI Application, Presentation, and Session map mainly to TCP/IP Application; Transport maps to Transport; Network maps to Internet; Data Link and Physical map to Network Access.",
44:"TCP/IP is called a protocol suite because it is a collection of cooperating protocols such as IP, TCP, UDP, DNS, and HTTP. The model describes how these protocols fit together.",
45:"The Internet layer commonly includes IPv4, IPv6, ICMP, and related IP protocols. Its main job is addressing and delivering packets between networks.",
46:"TCP and UDP are the main Transport-layer protocols. They provide different trade-offs between reliability, ordering, overhead, and application control.",
47:"HTTP, DNS, SMTP, SSH, FTP, and WebSocket are examples of Application-layer protocols. They define services and message formats used by applications.",
48:"The Network Access/Link layer represents local network delivery and the physical transmission system. Ethernet, Wi-Fi, and the underlying media fit here.",
49:"IP operates at the Internet or Network layer. It provides logical addressing and routes packets between different networks.",
50:"TCP and UDP operate at the Transport layer. They use port numbers to deliver data to the correct application process on a host.",
51:"HTTP operates at the Application layer. It defines how clients and servers exchange web requests, responses, headers, and content.",
52:"DNS is an Application-layer protocol. It translates names such as example.com into addresses and can also provide other naming information.",
53:"Ethernet primarily operates at the Data Link and Physical levels. It defines local frames, MAC addressing, signaling, and access to Ethernet media.",
54:"Application data is wrapped in a Transport segment, then an IP packet, then a link-layer frame. The receiver removes each wrapper in reverse order.",
55:"A logical model explains responsibilities and relationships between layers. An implementation stack is the actual software and hardware used to perform those functions.",
56:"TLS sits between application protocols and the Transport layer in common descriptions, but different models place it differently. Its functions do not fit perfectly into one OSI layer.",
57:"A socket is an operating-system communication endpoint associated with an IP address, transport protocol, and port. Applications use sockets to send and receive network data.",
58:"HTTPS uses an application request protected by TLS, carried over TCP in HTTP/1.1 or HTTP/2. The traffic is then carried in IP packets and link-layer frames.",
59:"TCP/IP maps closely to real Internet behavior and tools. Troubleshooting can therefore follow actual protocols such as DNS, IP, TCP, and HTTP.",
60:"OSI has seven layers while TCP/IP commonly has four; OSI is mainly a reference model, while TCP/IP is a practical protocol suite; their layer boundaries also differ.",
61:"A bit is a binary value, a symbol is a signaling unit representing one or more bits, and a signal is the physical electrical, optical, or radio representation.",
62:"Copper is inexpensive and common but has distance and interference limits. Fiber supports high speed and long distance, while wireless offers mobility but is more interference-sensitive.",
63:"Attenuation weakens a signal, distortion changes its shape, and noise adds unwanted energy. All three can reduce the receiver's ability to correctly recover data.",
64:"Baseband uses the medium for a signal over its main frequency range, while broadband divides available spectrum into multiple frequency channels.",
65:"Line encoding converts bits into physical signal patterns. It helps the receiver synchronize, detect transitions, and interpret the transmitted binary data.",
66:"Manchester encoding represents bits using transitions within each bit period. It was used in classic Ethernet and provides useful clock recovery.",
67:"A MAC address is a link-layer identifier used for local network communication. Ethernet and Wi-Fi interfaces commonly use 48-bit MAC addresses.",
68:"A MAC address is commonly written as six hexadecimal octets, such as 00:1A:2B:3C:4D:5E. Other separators or formats may also be used.",
69:"MAC addresses are intended to be globally unique when assigned by manufacturers, but duplicates can occur through mistakes, virtualization, spoofing, or misconfiguration.",
70:"A frame is a Data Link-layer unit containing addressing and control information around a network-layer packet. Ethernet frames also include error-detection information.",
71:"The Ethernet header carries addressing and control information, while the trailer contains the FCS. Together they support local delivery and error detection.",
72:"The Frame Check Sequence uses a CRC to detect corruption in an Ethernet frame. A receiver can discard a frame when the calculated value does not match.",
73:"CSMA/CD means Carrier Sense Multiple Access with Collision Detection. Older shared Ethernet devices listened before transmitting and detected collisions when they occurred.",
74:"Modern switched Ethernet normally uses dedicated full-duplex links, so collisions do not occur. Therefore CSMA/CD is largely a historical Ethernet mechanism.",
75:"CSMA/CA means Carrier Sense Multiple Access with Collision Avoidance. Wi-Fi uses it because a wireless device generally cannot reliably detect a collision while transmitting.",
76:"The hidden-node problem occurs when two wireless devices cannot hear each other but both can reach the access point. Their simultaneous transmissions can collide.",
77:"ARP maps an IPv4 address to a local MAC address. It sits conceptually between Network and Data Link functions because IP needs link-layer delivery information.",
78:"A VLAN logically separates one physical switched network into multiple Layer-2 networks. It improves segmentation, management, and control of broadcast traffic.",
79:"A switch forwarding table maps learned MAC addresses to switch ports. The switch uses it to decide where known destination frames should be sent.",
80:"If the destination MAC is unknown, the switch floods the frame out other ports in the same VLAN, except the port where it arrived.",
81:"A Layer-2 switch learns by examining the source MAC address of incoming frames. It records that MAC against the port and VLAN where it was seen.",
82:"MAC aging removes stale entries after a period of inactivity. This keeps the forwarding table current when devices move or network topology changes.",
83:"A switch normally floods a broadcast frame to all other ports in the same VLAN. It does not forward the broadcast into another VLAN without Layer-3 routing.",
84:"An unknown unicast is flooded within the VLAN because the switch does not yet know the destination port. Once learned, future frames can be forwarded directly.",
85:"Store-and-forward receives the entire frame before forwarding it. This allows the switch to check the FCS and discard corrupted frames before forwarding.",
86:"Cut-through begins forwarding after reading enough of the frame to determine the destination. It can reduce latency but may forward corrupted frames.",
87:"A VLAN creates a separate logical Layer-2 broadcast domain. It is useful for segmentation, security boundaries, and organizing devices independently of physical location.",
88:"An access port normally carries traffic for one VLAN to an end device. A trunk carries traffic for multiple VLANs, usually using 802.1Q tags.",
89:"IEEE 802.1Q adds VLAN identification information to Ethernet frames on trunk links. This lets switches distinguish traffic belonging to different VLANs.",
90:"The native VLAN is the VLAN whose traffic is sent untagged on an 802.1Q trunk. Both ends should be configured consistently to avoid problems.",
91:"VLAN segmentation separates users and traffic into different broadcast domains. This reduces unnecessary broadcasts and can improve security and management.",
92:"Devices in different VLANs are in different Layer-2 networks, so they cannot communicate directly through ordinary switching. They need Layer-3 routing between VLANs.",
93:"A router or Layer-3 switch provides the Layer-3 gateway functions needed to move packets between different VLAN subnets.",
94:"Inter-VLAN routing is routing traffic between VLANs. A router interface, router-on-a-stick, or Layer-3 switch can perform this function.",
95:"A trunk link carries multiple VLANs over one physical connection. VLAN tags identify which logical network each frame belongs to.",
96:"VLAN hopping is an attack or misconfiguration that lets traffic cross VLAN boundaries unexpectedly. Strong trunk configuration and unused native VLAN practices help reduce risk.",
97:"STP, or Spanning Tree Protocol, prevents Layer-2 switching loops. It logically blocks redundant paths while keeping them available as backups.",
98:"A switching loop can cause repeated frames, broadcast storms, unstable MAC tables, and severe network congestion. It can make the entire LAN unusable.",
99:"STP elects a root bridge and calculates loop-free paths. Redundant links are placed into a blocking state until they are needed.",
100:"A hub sends traffic out all ports and shares one collision domain. A switch learns MAC addresses and forwards frames selectively, normally giving each port its own collision domain.",
101:"An IP address is a logical address assigned to a network interface. It identifies a host or interface for communication across an IP network.",
102:"IPv4 uses 32 bits because its original design provided about 4.3 billion possible addresses. That space is now insufficient for the modern Internet.",
103:"IPv4 is written as four decimal octets separated by dots, such as 192.168.1.10. Each octet represents 8 bits and ranges from 0 to 255.",
104:"The network portion identifies the subnet to which an address belongs. Its size is determined by the subnet mask or CIDR prefix length.",
105:"The host portion identifies a device within a particular subnet. The number of host bits determines how many addresses that subnet can contain.",
106:"A subnet mask marks which IPv4 bits represent the network and which represent hosts. For example, /24 corresponds to 255.255.255.0.",
107:"CIDR represents an address and prefix length together, such as 192.168.1.0/24. It replaced the older fixed class-based approach with flexible prefixes.",
108:"/24 means the first 24 bits are the network portion and 8 bits remain for hosts. A traditional /24 contains 256 total addresses.",
109:"A network address identifies the subnet itself and normally cannot be assigned to a host. A host address identifies an interface within that subnet.",
110:"A broadcast address targets all hosts in an IPv4 subnet. It is formed by setting all host bits to 1, such as 192.168.1.255 for a /24.",
111:"127.0.0.1 is the common IPv4 loopback address. Traffic sent there stays inside the local host and is useful for testing software and networking.",
112:"Private IPv4 ranges are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. They are intended for internal networks and are not globally routed.",
113:"APIPA or IPv4 link-local addressing uses 169.254.0.0/16 when a host cannot obtain an address normally. It supports limited local communication.",
114:"0.0.0.0 can mean an unspecified address or represent the default route when used with a /0 prefix. Its exact meaning depends on context.",
115:"255.255.255.255 is the IPv4 limited broadcast address. It reaches hosts on the local broadcast domain and is not routed across normal routers.",
116:"Public IPv4 addresses can be globally routed on the Internet. Private addresses are used internally and normally require NAT or another mechanism for Internet access.",
117:"An IPv4 /24 has 2^(32-24) = 256 total addresses. Traditionally, 254 are usable host addresses because network and broadcast addresses are reserved.",
118:"A /26 has 2^6 = 64 total addresses. Traditionally, 62 are usable hosts after excluding the network and broadcast addresses.",
119:"Apply the same subnet mask to both addresses and compare their network portions. If the resulting network addresses match, they are in the same subnet.",
120:"Classful addressing used fixed A, B, and C network sizes. Classless addressing uses arbitrary prefix lengths, making address allocation and routing more efficient.",
121:"Subnetting divides one IP network into smaller networks. It improves address utilization, segmentation, routing control, and broadcast containment.",
122:"Each subnet is a separate Layer-3 network, so broadcasts do not normally cross the router between them. This effectively reduces the size of each broadcast domain.",
123:"A /30 leaves 2 host bits, giving 2^2 = 4 total addresses. Traditionally, 2 are usable host addresses, making /30 common on point-to-point links.",
124:"A /29 leaves 3 host bits, so it contains 8 total addresses. Traditionally, 6 are usable host addresses after reserving network and broadcast.",
125:"/16 = 255.255.0.0, /20 = 255.255.240.0, /24 = 255.255.255.0, and /28 = 255.255.255.240.",
126:"The network address is found by bitwise ANDing the IP address with the subnet mask. In simple terms, keep network bits and set host bits to zero.",
127:"The broadcast address is found by keeping the network bits and setting every host bit to one. It is the last address in the subnet.",
128:"The first usable host is network address + 1, and the last usable host is broadcast address - 1 in traditional IPv4 subnets.",
129:"The subnet increment is the block size in the octet where the mask is not 255 or 0. It can be found as 256 minus the mask value in that octet.",
130:"Borrow 2 host bits from /24 to create /26, giving four equal subnets. They start at 192.168.10.0, .64, .128, and .192.",
131:"Borrow 3 bits from /24 to create /27, giving eight equal subnets. Each subnet has 32 addresses and traditionally 30 usable hosts.",
132:"VLSM, or Variable Length Subnet Masking, allows different subnets to use different prefix lengths. This lets each department receive a suitable block size.",
133:"Fixed-size subnetting gives every subnet the same number of addresses, which can waste space. VLSM assigns sizes according to actual host requirements.",
134:"Use the largest required block first: 100 hosts needs /25, 50 needs /26, 25 needs /27, and 10 needs /28. Allocate them sequentially without overlap.",
135:"Route aggregation combines several contiguous networks into one larger prefix. Routers can then advertise one summary route instead of many individual routes.",
136:"CIDR allows multiple routes to be represented by a common prefix. Fewer advertised entries mean smaller routing tables and simpler routing decisions.",
137:"No, with /24 the networks are 192.168.1.0/24 and 192.168.2.0/24. They are different subnets, so communication requires a router or Layer-3 device.",
138:"No. With /16, 172.16.1.10 belongs to 172.16.0.0/16 while 172.17.1.10 belongs to 172.17.0.0/16, so they are different subnets.",
139:"A /31 provides exactly two addresses and is useful on point-to-point links where network and broadcast addresses are not needed in the traditional way.",
140:"For 172.16.35.77/27, the block size is 32. The network is 172.16.35.64, broadcast is 172.16.35.95, and usable hosts are .65 through .94.",
141:"IPv6 was introduced mainly because IPv4 address space was running out. It also improves addressing structure, autoconfiguration, and some aspects of protocol design.",
142:"An IPv6 address is 128 bits long. This provides an extremely large address space compared with IPv4's 32 bits.",
143:"IPv6 is written as eight groups of four hexadecimal digits separated by colons, for example 2001:db8:0:0:0:0:0:1.",
144:"Leading zeros in each group can be removed, and one longest consecutive run of all-zero groups can be replaced with ::. The compression can be used only once.",
145:"A global unicast address is an IPv6 address intended for globally routable communication. It is broadly similar to a public IPv4 address.",
146:"A link-local IPv6 address is normally in fe80::/10. It is valid only on the local link and is heavily used for neighbor and router communication.",
147:"The IPv6 loopback address is ::1. Like 127.0.0.1 in IPv4, it refers back to the same host.",
148:"The IPv6 unspecified address is ::. It means 'no address specified' and is commonly used before a host has configured a usable address.",
149:"IPv4 uses 32-bit addresses, while IPv6 uses 128-bit addresses. IPv6 therefore provides a vastly larger address space.",
150:"No. IPv6 deliberately does not use traditional broadcast addressing. It uses multicast for many one-to-many discovery functions.",
151:"IPv6 uses multicast, and in some cases anycast, instead of broadcast. Neighbor Discovery uses multicast groups for local discovery.",
152:"Neighbor Discovery Protocol is an IPv6 ICMPv6-based mechanism for finding neighbors, routers, and link-layer addresses. It also supports address configuration functions.",
153:"IPv6 uses Neighbor Discovery messages instead of ARP. A host sends ICMPv6 Neighbor Solicitation to discover the link-layer address of a neighbor.",
154:"SLAAC means Stateless Address Autoconfiguration. Hosts use router advertisements to learn network prefixes and automatically construct IPv6 addresses.",
155:"DHCPv6 is the IPv6 version of DHCP-style configuration. It can provide addresses and other configuration information, depending on the network design.",
156:"SLAAC can let a host configure an address from router advertisements with little server state. DHCPv6 can provide centrally managed configuration and additional options.",
157:"Dual-stack means a device or network runs IPv4 and IPv6 simultaneously. It allows communication with both IPv4-only and IPv6-capable systems.",
158:"Tunneling carries one IP version inside another, while translation converts traffic between IPv4 and IPv6. These approaches help networks migrate gradually.",
159:"A /64 leaves 64 bits for interface addressing and is the common size for IPv6 LAN subnets. It works well with standard IPv6 autoconfiguration.",
160:"IPv6 has 128-bit addresses, no header checksum, no broadcast, and uses extension headers. Its base header is fixed at 40 bytes and simplified compared with IPv4.",
161:"ARP, Address Resolution Protocol, maps an IPv4 address to a MAC address on a local network. It allows IP packets to be placed into Ethernet frames.",
162:"An IPv4 host knows the destination IP but Ethernet needs a destination MAC. ARP discovers that MAC when the destination is on the local LAN.",
163:"The sender broadcasts an ARP request asking who owns an IP address. The device with that IP replies with its MAC address.",
164:"The sender initially does not know which MAC owns the target IP. Broadcasting lets every device on the local LAN inspect the request.",
165:"After learning the requester's MAC, the target can send the ARP reply directly. Therefore the reply is normally unicast.",
166:"An ARP cache stores recently learned IP-to-MAC mappings. It avoids repeating ARP broadcasts for every packet sent to the same local host.",
167:"ARP spoofing sends forged ARP messages to associate an attacker's MAC with another device's IP. This can redirect local traffic unexpectedly.",
168:"By making victims associate the attacker's MAC with a gateway or another host, traffic can pass through the attacker. The attacker can then observe or alter it.",
169:"Gratuitous ARP is an unsolicited ARP message about a host's own IP. It can update caches, detect duplicate addresses, or announce a changed MAC.",
170:"ICMP is a control and diagnostic protocol carried by IP. It reports conditions such as unreachable destinations and supports tools such as ping.",
171:"An ICMP echo request asks whether a host can respond, and an echo reply is the response. Together they are commonly used by ping.",
172:"Ping sends ICMP Echo Requests and waits for Echo Replies. It measures reachability and approximate round-trip time when ICMP is allowed.",
173:"ICMP Destination Unreachable tells a sender that a packet cannot be delivered. Different codes can indicate network, host, port, or other reasons.",
174:"ICMP Time Exceeded is generated when a packet's TTL or hop limit reaches zero. Traceroute uses this behavior to discover intermediate hops.",
175:"Traceroute sends packets with increasing TTL values. Each expired TTL causes an ICMP Time Exceeded response, revealing the router at that hop.",
176:"Ping may be blocked by a firewall or host policy even when application traffic is allowed. So failed ICMP does not always mean the host is unreachable.",
177:"Path MTU Discovery determines the largest packet size that can travel end-to-end without fragmentation. It helps avoid fragmentation-related problems and inefficient packets.",
178:"ARP resolves an IPv4 address to a local MAC address. DNS resolves names to IP addresses and other records, usually across a wider network.",
179:"For a local destination, the sender ARPs for its MAC, builds an Ethernet frame containing the IP packet, and sends it directly to that host.",
180:"For a remote destination, the sender sends the frame to the default gateway's MAC. The router then forwards the IP packet toward the remote network.",
181:"Routing is the process of deciding which path or next hop should be used to reach a destination network. Routers use routing information to make this decision.",
182:"Forwarding is the actual per-packet action of selecting an outgoing interface or next hop. Routing builds or learns the information used for forwarding.",
183:"A routing table contains routes and path information used for decisions. A forwarding table is the optimized structure used to make fast packet-by-packet forwarding decisions.",
184:"A routing table commonly stores destination prefixes, next hops, outgoing interfaces, metrics, and route sources. Exact fields depend on the operating system or router.",
185:"A default route matches destinations for which no more specific route exists. In IPv4 it is commonly written as 0.0.0.0/0.",
186:"The next hop is the immediate router or neighbor to which a packet should be sent. It is one step closer to the final destination.",
187:"A directly connected route represents a network attached to one of the router's interfaces. The router can reach it without another router as the next hop.",
188:"A static route is manually configured by an administrator. It is simple and predictable but does not automatically adapt to topology changes.",
189:"Dynamic routing uses routing protocols to learn and update routes automatically. It is useful for larger or changing networks.",
190:"Longest-prefix matching chooses the route with the most matching destination bits. A more specific prefix therefore normally takes precedence over a broader route.",
191:"A more specific route gives a more precise description of where the destination belongs. Routers prefer it because it narrows the forwarding choice.",
192:"If no specific route matches, the router uses a default route if one exists. If there is no usable default route, the packet is normally dropped.",
193:"Administrative distance is a preference value used by some routers to choose between routes learned from different sources. Lower values are generally preferred in Cisco-style routing.",
194:"A routing metric measures the cost or preference of a path. Protocols may use hop count, bandwidth, delay, or a composite calculation.",
195:"Route convergence is the process of routers reaching a consistent view of the network after a change. Slow convergence can cause temporary routing problems.",
196:"A routing loop occurs when packets are repeatedly forwarded between routers without reaching the destination. TTL eventually limits the lifetime of the packets.",
197:"TTL limits how many router hops an IPv4 packet can survive. Each router decreases it, and a packet is discarded when it reaches zero.",
198:"Asymmetric routing means the forward and return traffic use different paths. It is common on large networks but can complicate troubleshooting and stateful firewalls.",
199:"Policy-based routing selects paths using rules such as source address, application, or other criteria rather than only the destination-based routing table.",
200:"Route summarization combines several routes into a broader prefix when their addresses can be represented together. This reduces routing information and improves scalability.",
201:"A router receives a frame, checks the IP packet, finds the best route using longest-prefix matching, decrements TTL, rewrites the link-layer header, and forwards the packet.",
202:"Distance-vector routers learn route information from neighbors and usually share distance information. Link-state routers build a topology view and calculate paths from it.",
203:"RIP is a distance-vector routing protocol. Its classic metric is hop count, with 15 as the maximum usable hop count.",
204:"Count-to-infinity occurs when routers gradually increase a route's metric while incorrectly believing a failed destination is reachable through each other.",
205:"Split horizon prevents a router from advertising a route back through the interface from which it learned that route. This helps reduce routing loops.",
206:"Route poisoning advertises a failed route with an intentionally unreachable metric. It helps other routers quickly learn that the destination is no longer usable.",
207:"OSPF is a link-state interior gateway routing protocol. It uses a topology database and SPF calculations to choose paths within an autonomous system.",
208:"OSPF is link-state because routers advertise information about their links rather than simply advertising distances. Each router builds a topology view from that information.",
209:"An OSPF area is a logical subdivision of an OSPF network. Areas reduce the size of routing information and SPF calculations.",
210:"Area 0 is the OSPF backbone area. Other OSPF areas normally connect to it to exchange inter-area routing information.",
211:"An OSPF neighbor adjacency is a relationship between OSPF routers that exchange routing information. The exact adjacency states depend on the network type and router roles.",
212:"The link-state database contains learned link-state advertisements describing the OSPF topology. Routers use it as input to calculate routes.",
213:"OSPF uses Dijkstra's Shortest Path First algorithm to calculate the best paths from the router to destinations in its link-state database.",
214:"BGP, Border Gateway Protocol, exchanges reachability information between autonomous systems. It is the main inter-domain routing protocol of the Internet.",
215:"BGP is path-vector because routes carry path attributes such as AS_PATH. Routers can use these attributes to apply policies and avoid loops.",
216:"eBGP exchanges routes between different autonomous systems, while iBGP distributes BGP information within the same autonomous system.",
217:"An Autonomous System is a network or group of networks under one administrative routing policy. Each AS is identified by an ASN.",
218:"AS_PATH records autonomous systems a BGP route has crossed and helps prevent loops. Local preference is an internal policy value used to prefer outbound paths.",
219:"BGP connects independently operated networks across the public Internet. It allows large organizations and providers to exchange and control reachability information.",
220:"RIP is simple and uses hop count; OSPF is link-state and common inside organizations; BGP is policy-driven path-vector routing between autonomous systems.",
221:"Software engineers may need BGP knowledge when debugging cloud/CDN connectivity, Internet routing incidents, multi-region systems, or provider-related reachability problems.",
222:"TCP is a connection-oriented Transport protocol that provides reliable, ordered delivery of a byte stream. It is widely used by web and application services.",
223:"TCP is connection-oriented because endpoints establish shared state before sending application data. This state supports sequencing, acknowledgments, flow control, and retransmission.",
224:"TCP provides ordered, reliable delivery and detects lost or corrupted data. It does not guarantee low latency, infinite reliability, or that the remote application is healthy.",
225:"A TCP segment is the Transport-layer unit carrying TCP header information and application bytes. It is encapsulated inside an IP packet.",
226:"TCP source and destination ports identify the sending and receiving application processes. Together with IP addresses they identify the communication endpoints.",
227:"A TCP sequence number identifies the position of bytes in the byte stream. It lets the receiver detect missing, duplicate, or out-of-order data.",
228:"The acknowledgment number indicates the next byte the receiver expects. It therefore confirms receipt of all earlier bytes in sequence.",
229:"The three-way handshake is SYN, SYN-ACK, then ACK. It establishes sequence-number state and confirms that both endpoints can communicate.",
230:"The client sends SYN with an initial sequence number. It is requesting a TCP connection and synchronizing sequence-number state.",
231:"The server replies with SYN-ACK, acknowledging the client's SYN and sending its own initial sequence number. This shows the server is ready to continue.",
232:"The client sends the final ACK acknowledging the server's SYN. The connection is then established and application data can be exchanged.",
233:"Sequence numbers let TCP identify byte positions and preserve ordering. They also allow missing data to be detected and retransmitted.",
234:"TCP uses sequence numbers, acknowledgments, checksums, timers, and retransmissions to provide reliable ordered delivery despite packet loss.",
235:"Retransmission means sending data again after TCP believes it was lost or not acknowledged. It can be triggered by a timeout or duplicate acknowledgments.",
236:"A TCP timeout occurs when expected acknowledgment or progress does not arrive within an estimated time. TCP then retransmits and adjusts its sending behavior.",
237:"A duplicate ACK repeats an acknowledgment for the same missing sequence range. Multiple duplicate ACKs can indicate a gap and trigger fast retransmit.",
238:"Fast retransmit resends likely-lost data after several duplicate ACKs instead of waiting for the retransmission timeout. This improves recovery speed.",
239:"Cumulative acknowledgment confirms receipt of all bytes up to a certain point. One ACK can therefore acknowledge multiple segments that arrived in order.",
240:"SACK lets a receiver report specific blocks that arrived successfully even when another block is missing. TCP can then retransmit only the missing data.",
241:"TCP adds connection setup, acknowledgments, ordering, retransmission, and congestion control. These mechanisms add overhead and can increase latency compared with UDP.",
242:"Flow control prevents a fast sender from overwhelming a slow receiver. TCP uses the receiver's advertised window to limit outstanding unacknowledged data.",
243:"The receive window tells the sender how much additional data the receiver can currently accept. It is part of TCP flow control.",
244:"Sliding windows allow multiple bytes or segments to be in flight before acknowledgments arrive. The sending window moves forward as data is acknowledged.",
245:"Congestion control prevents senders from overwhelming the network itself. TCP changes its sending rate based on signals such as loss and delay.",
246:"Flow control protects the receiving host, while congestion control protects the network path. TCP considers both when deciding how much data to send.",
247:"The congestion window, or cwnd, limits how much unacknowledged data TCP may have in the network. It changes according to congestion-control behavior.",
248:"Slow start begins with a relatively small congestion window and increases it rapidly as acknowledgments arrive. It helps TCP discover available capacity.",
249:"Congestion avoidance grows the congestion window more cautiously than slow start. The goal is to use capacity while reducing the chance of congestion.",
250:"AIMD means Additive Increase, Multiplicative Decrease. TCP gradually increases its sending rate and sharply reduces it after congestion is detected.",
251:"Fast recovery is a TCP mechanism for recovering from detected packet loss without returning all the way to the smallest sending rate. Exact behavior depends on TCP version.",
252:"Retransmission timeout, or RTO, is the estimated wait time before TCP assumes an unacknowledged segment may be lost. It is calculated from measured network timing.",
253:"After loss, TCP reduces its sending rate by lowering congestion-window-related state. The exact reduction depends on whether loss was detected by timeout or duplicate ACKs.",
254:"Head-of-line blocking means later TCP data cannot be delivered to the application until missing earlier bytes are recovered. This can increase application delay.",
255:"TCP keepalive sends occasional probes on an otherwise idle connection. It can help detect dead peers or broken paths, although application-level heartbeats are also common.",
256:"FIN indicates a normal request to finish a direction of a TCP connection. RST abruptly resets a connection when normal termination or recovery is not appropriate.",
257:"Normal termination uses FIN and ACK in each direction, often producing four segments. Each endpoint independently closes its sending side.",
258:"TIME_WAIT occurs after active TCP closure to handle delayed segments and allow the final connection state to expire safely.",
259:"TIME_WAIT prevents delayed packets from an old connection from interfering with a new connection using the same connection identifiers. It also supports reliable final ACK handling.",
260:"A half-close means one side has finished sending but can still receive data. TCP supports independent shutdown of the two directions.",
261:"If a TCP segment targets a closed port, the host normally responds with a TCP RST. This tells the sender that no listening service exists there.",
262:"UDP is a connectionless Transport protocol that sends independent datagrams. It has low overhead and does not provide built-in reliability or ordering.",
263:"UDP is connectionless because it does not establish a persistent transport session before sending datagrams. Each datagram is handled independently.",
264:"A UDP header contains source port, destination port, length, and checksum fields. The header is only 8 bytes long.",
265:"TCP has a larger and more feature-rich header, normally at least 20 bytes. UDP has an 8-byte header and therefore lower basic overhead.",
266:"DNS often uses UDP because queries and responses are usually small and do not need connection setup. TCP is also used when required, such as for larger transfers.",
267:"Real-time media often prefers UDP because it avoids retransmission delays. Applications can choose how to handle loss while keeping latency low.",
268:"UDP does not guarantee delivery, ordering, duplicate suppression, or retransmission. Those responsibilities can be implemented by the application when needed.",
269:"An application can add sequence numbers, acknowledgments, timers, retransmissions, checksums, and congestion control on top of UDP to build its own reliable protocol.",
270:"A port number identifies a transport-layer endpoint associated with an application process. TCP and UDP each have their own port-number space.",
271:"An IP address identifies the host or interface, not the exact application. Ports let many applications communicate simultaneously on the same host.",
272:"A socket is an OS-level endpoint used by an application for network communication. It is associated with an address, port, and transport protocol.",
273:"A TCP connection is commonly identified by the four-tuple: source IP, source port, destination IP, and destination port. The protocol is TCP.",
274:"Well-known ports are the lower-numbered ports traditionally assigned to common services. Examples include 22 for SSH, 53 for DNS, and 443 for HTTPS.",
275:"Ephemeral ports are temporary client-side ports chosen for outbound connections. The operating system normally allocates them from a configured dynamic range.",
276:"Port 80 is conventionally used for HTTP. Modern websites often redirect or otherwise move users to HTTPS on port 443.",
277:"Port 443 is conventionally used for HTTPS, meaning HTTP protected with TLS. The exact application can vary by configuration.",
278:"Port 53 is used by DNS. DNS commonly uses UDP 53 for ordinary queries and TCP 53 for cases requiring TCP transport.",
279:"Port 22 is conventionally used by SSH, a secure protocol for remote login and other encrypted communication.",
280:"Port 25 is conventionally used for SMTP server-to-server mail transfer. Submission by mail clients commonly uses other ports such as 587.",
281:"Two processes generally cannot bind the same IP/port/protocol combination at the same time. Exceptions depend on OS features, different local addresses, or socket options.",
282:"DNS, the Domain Name System, translates human-friendly names into IP addresses and other records. It forms a distributed naming system for the Internet.",
283:"Humans remember names more easily than numeric IP addresses, and IP addresses can change. DNS provides a stable naming layer that can map names to current services.",
284:"A domain name is a hierarchical name such as example.com. It consists of labels arranged under the DNS root and top-level domains.",
285:"A hostname is a name assigned to a host or network interface, such as server1.example.com. It can be a complete domain name or a local host label.",
286:"A DNS resolver is the component that obtains DNS answers for clients. It may use cached data or query other DNS servers recursively or iteratively.",
287:"In a recursive query, the DNS server contacted by the client is asked to obtain the final answer on the client's behalf.",
288:"In an iterative query, a DNS server responds with the best information it has, often referring the requester to another DNS server.",
289:"Root DNS servers provide referrals to the appropriate top-level-domain servers. They are at the top of the public DNS hierarchy.",
290:"A TLD server handles a top-level domain such as .com or .org. It directs resolvers toward authoritative servers for individual domains.",
291:"An authoritative DNS server stores the official DNS records for a domain. It provides the final answer for names within the zones it serves.",
292:"A resolver checks its cache, then may query a root server, the TLD server, and the authoritative server for example.com. The result is returned and often cached.",
293:"DNS caching stores previously obtained answers for a period of time. It reduces query traffic and speeds up repeated name lookups.",
294:"A DNS record TTL tells caches how long an answer may be stored before it should be refreshed. Lower TTLs allow faster changes but increase query traffic.",
295:"An A record maps a hostname to an IPv4 address. Example: www.example.com → 192.0.2.10.",
296:"An AAAA record maps a hostname to an IPv6 address. It is the IPv6 counterpart of the DNS A record.",
297:"A CNAME record creates an alias from one DNS name to another canonical name. The resolver then follows the target name to obtain its address.",
298:"An MX record specifies mail servers responsible for receiving email for a domain. It includes a preference value used to choose among servers.",
299:"An NS record identifies authoritative name servers for a DNS zone or domain delegation. It helps resolvers find where the domain's DNS data is hosted.",
300:"A PTR record supports reverse DNS, mapping an IP address back to a name. IPv4 reverse lookups commonly use the in-addr.arpa domain.",
301:"If DNS resolution fails, the client may not know the server's IP address even though the network itself works. Check resolver configuration, connectivity, records, and caching.",
302:"HTTP is an Application-layer protocol for transferring web resources using requests and responses. It is the foundation of the modern Web.",
303:"HTTP is request-response because a client sends a request describing an operation and a server returns a response containing status and optional data.",
304:"An HTTP request contains a method, target/URL information, headers, and optionally a body. The exact fields depend on the HTTP version and request.",
305:"An HTTP response contains a status code, headers, and optionally a body. The body may contain HTML, JSON, images, or other content.",
306:"An HTTP method indicates the intended operation on a resource. Common methods include GET, POST, PUT, PATCH, and DELETE.",
307:"GET is normally used to retrieve data and should not change server state. POST commonly submits data or creates a server-side operation and is not generally idempotent.",
308:"PUT is commonly used to create or completely replace a resource at a known target URI. Repeating the same PUT is intended to have the same effect.",
309:"PATCH is used for partial modification of an existing resource. It is useful when only selected fields need to change.",
310:"DELETE requests removal of a resource. Repeating DELETE may produce different status responses, but the intended resource-removal effect is generally idempotent.",
311:"An idempotent operation has the same intended server-side effect when repeated. GET, PUT, and DELETE are defined as idempotent methods, while POST is not.",
312:"HTTP headers carry metadata about requests and responses. Examples include Host, Content-Type, Authorization, Cache-Control, and cookies.",
313:"The Host header identifies the requested host name. It allows many websites to share the same IP address through virtual hosting.",
314:"Content-Type tells the receiver what media type the message body contains, such as application/json or text/html. It helps the receiver interpret the body correctly.",
315:"Content-Length gives the size of a message body in bytes when used. It helps the receiver know how much body data is expected.",
316:"Cookies are small pieces of state stored by a browser and sent with matching requests. They are commonly used for sessions, preferences, and tracking.",
317:"HTTP caching stores responses so they can be reused without contacting the origin every time. This reduces latency, bandwidth use, and server load.",
318:"Cache-Control is an HTTP header that specifies caching rules such as max-age, no-store, or public/private behavior.",
319:"An HTTP status code is a three-digit result describing the outcome of a request. It tells the client whether the operation succeeded, redirected, or failed.",
320:"2xx means successful, 3xx means redirection, 4xx indicates a client-side/request problem, and 5xx indicates a server-side failure.",
321:"HTTP/1.1 commonly uses sequential requests over connections; HTTP/2 multiplexes streams over one connection; HTTP/3 uses QUIC over UDP for improved transport behavior.",
322:"HTTPS protects HTTP with TLS. It provides encryption, integrity, and server authentication, reducing the risk of eavesdropping and tampering.",
323:"TLS is a security protocol that protects application traffic over a network. It is widely used to secure HTTPS and other protocols.",
324:"TLS provides confidentiality, integrity, and authentication of the server through certificates. It can also support client authentication when configured.",
325:"HTTPS is HTTP carried through a TLS-protected connection. TLS protects the HTTP messages while the HTTP semantics remain largely the same.",
326:"A simplified TLS handshake negotiates cryptographic parameters, authenticates the server using a certificate, and establishes shared session keys. Application data is then encrypted.",
327:"A digital certificate binds an identity, such as a domain name, to a public key. A trusted Certificate Authority signs it so clients can validate the binding.",
328:"A Certificate Authority, or CA, is a trusted organization that issues and signs digital certificates. Browsers and operating systems maintain trusted CA roots.",
329:"Certificate chain validation checks signatures from the server certificate through intermediate certificates to a trusted root. It also checks validity, hostname, and other constraints.",
330:"A public key can be shared openly and is used for operations such as encryption or signature verification. It has a mathematically related private key.",
331:"A private key must be kept secret by its owner. It is used for operations such as decryption or creating digital signatures, depending on the algorithm.",
332:"Asymmetric cryptography helps establish trust and exchange or derive secret material without already sharing a symmetric key. It is computationally more expensive than symmetric encryption.",
333:"Symmetric cryptography is much faster for large amounts of data. After the handshake establishes session keys, bulk application traffic is normally protected symmetrically.",
334:"Forward secrecy means a later compromise of a long-term private key should not reveal past session data. Modern TLS commonly achieves this using ephemeral key exchange.",
335:"Certificate expiration means the certificate is no longer valid after its validity period. Clients may reject it even if the certificate was otherwise correctly signed.",
336:"If the certificate name does not match the requested hostname, the client cannot verify that the certificate belongs to that site. Browsers normally show a security error.",
337:"Certificate pinning restricts accepted certificates or public keys to expected values. It can reduce some MITM risks but must be managed carefully to avoid outages.",
338:"A man-in-the-middle attack places an attacker between two communicating parties. The attacker attempts to observe or modify traffic while appearing legitimate.",
339:"TLS encrypts application traffic so passive observers cannot normally read its contents. Integrity protection also helps detect unauthorized modification.",
340:"HSTS tells browsers to use HTTPS for a site and avoid insecure HTTP connections. It helps prevent downgrade and accidental plaintext access.",
341:"Encryption protects data using a reversible key-based process; hashing creates a one-way digest; encoding changes representation without providing security by itself.",
342:"HTTPS protects data in transit but does not authenticate users or control application permissions. Applications still need login, authorization, validation, and session management.",
343:"DHCP automatically provides hosts with IP configuration. It reduces manual setup and helps centrally manage addresses and related network settings.",
344:"DHCP is useful because clients can automatically receive addresses, subnet masks, gateways, DNS servers, and lease information instead of being configured manually.",
345:"DORA stands for Discover, Offer, Request, and Acknowledgment. It describes the common four-step DHCP address allocation process.",
346:"DHCP Discover is a client broadcast asking for configuration because the client may not yet have a usable IP address or know the DHCP server.",
347:"A DHCP Offer is a server's proposed configuration, commonly including an IP address, lease duration, subnet mask, gateway, and DNS information.",
348:"A DHCP Request tells the selected DHCP server that the client wants the offered configuration. It can also indicate which offer was chosen.",
349:"A DHCP Acknowledgment confirms the lease and configuration. The client can then configure its interface and use the assigned settings.",
350:"DHCP can provide subnet masks, default gateways, DNS servers, lease durations, domain information, and many other options depending on configuration.",
351:"A DHCP lease gives a client temporary rights to use an assigned IP configuration. The client normally renews the lease before it expires.",
352:"When a lease expires without successful renewal, the client may stop using the address and restart address acquisition. Exact behavior follows the DHCP state process.",
353:"NAT, Network Address Translation, changes address information as traffic crosses a router or gateway. It is commonly used to connect private IPv4 networks to public addresses.",
354:"NAT is widely used because private IPv4 addresses are not globally routable and public IPv4 addresses are scarce. Many devices can therefore share fewer public addresses.",
355:"Static NAT maps a particular private address to a particular public address. The mapping normally remains fixed.",
356:"Dynamic NAT maps private addresses to public addresses from a configured pool. The mapping is temporary and depends on available addresses.",
357:"PAT, or NAT overload, maps many private connections to one or a few public addresses by using different source port numbers.",
358:"The router records translations using combinations of private IP/port and public IP/port. Return packets are matched to the correct internal connection.",
359:"Port forwarding creates a rule that sends traffic arriving at a public IP and port to a specific internal host and port.",
360:"NAT can make direct inbound connections difficult because endpoints do not have globally reachable addresses. Applications may need traversal techniques, relays, or explicit port mappings.",
361:"NAT mainly translates addresses and ports; it does not inherently inspect traffic as a security policy engine. A firewall makes explicit allow/deny decisions.",
362:"The client creates a private source IP/port, the router replaces it with a public IP/port, the request travels to the server, and the router reverses the mapping for the reply.",
363:"A repeater regenerates or reshapes a signal to extend transmission distance. It mainly operates at the Physical layer.",
364:"A hub is a multiport Physical-layer repeater. It sends incoming signals out other ports rather than making forwarding decisions using MAC addresses.",
365:"A bridge connects Layer-2 network segments and forwards frames using MAC addresses. Modern switches are essentially high-performance multiport bridges.",
366:"A Layer-2 switch forwards Ethernet frames using MAC addresses and VLAN information. It normally separates collision domains at its ports.",
367:"A Layer-3 switch performs switching plus routing functions. It can route between IP subnets or VLANs at high speed.",
368:"A router connects different IP networks and forwards packets using Layer-3 addresses. It separates broadcast domains by default.",
369:"A gateway is a device or service that acts as an entry or exit point and may translate between different networks or protocols. The term is broader than router.",
370:"A modem converts or adapts signals for a particular access technology, such as cable, DSL, or some other provider medium. It connects customer equipment to the access network.",
371:"An access point provides wireless clients with access to a wired or other network. It bridges wireless traffic into the LAN and manages Wi-Fi radio functions.",
372:"A firewall enforces traffic-control rules between networks or hosts. It can allow, block, inspect, and log traffic according to configured policies.",
373:"A proxy server acts on behalf of clients when accessing other services. It can provide filtering, caching, privacy controls, or policy enforcement.",
374:"A reverse proxy sits in front of servers and receives client requests on their behalf. It can provide TLS termination, routing, caching, security, and load balancing.",
375:"A load balancer distributes client traffic across multiple backend servers. It improves availability, scalability, and sometimes performance.",
376:"A switch mainly forwards frames within a Layer-2 network using MAC addresses. A router forwards IP packets between different networks using routing information.",
377:"A hub repeats traffic to all ports and creates one shared collision domain. A switch learns MAC addresses and normally sends frames only toward the required port.",
378:"A forward proxy represents clients to external servers. A reverse proxy represents servers to clients and is commonly used for protection, routing, and scaling.",
379:"The default gateway is the router a host uses to reach destinations outside its local subnet. The host sends remote traffic to the gateway's MAC address.",
380:"A home router commonly combines routing, NAT/PAT, DHCP, firewalling, Wi-Fi access-point functions, and sometimes DNS forwarding in one device.",
381:"A router or Layer-3 boundary separates broadcast domains. Different VLANs are also separate broadcast domains when configured normally.",
382:"A switch creates separate collision domains for its individual Ethernet ports. With full-duplex switched Ethernet, collisions are normally eliminated.",
383:"Wi-Fi is a family of wireless LAN technologies based on IEEE 802.11. It lets devices communicate over radio instead of physical Ethernet cables.",
384:"IEEE 802.11 is the family of standards defining Wi-Fi wireless LAN operation. Different amendments specify radio bands, speeds, security, and other features.",
385:"Ethernet normally uses wired links and offers stable, predictable performance. Wi-Fi uses shared radio channels, providing mobility but more sensitivity to interference and distance.",
386:"SSID is the Wi-Fi network name shown to users. BSSID identifies a particular wireless access point/radio, commonly represented by a MAC address.",
387:"An access point connects wireless clients to a network and coordinates wireless communication. It often bridges Wi-Fi traffic to a wired LAN.",
388:"Infrastructure mode uses access points as the central connection point for wireless clients. Most normal Wi-Fi networks operate this way.",
389:"Ad hoc networking lets wireless devices communicate directly without a traditional access point. It is useful for limited peer-to-peer wireless scenarios.",
390:"CSMA/CA listens before transmission and uses mechanisms to reduce the chance of collisions. Wi-Fi uses it because detecting collisions during transmission is difficult.",
391:"A wireless device cannot reliably listen for collisions while transmitting because its own signal overwhelms received signals. Therefore Wi-Fi uses avoidance rather than collision detection.",
392:"RTS/CTS lets a device reserve the wireless medium before sending larger frames. It can reduce hidden-node collisions but adds overhead.",
393:"The hidden-node problem occurs when two transmitters cannot hear each other but both reach the same receiver. Their transmissions can collide at that receiver.",
394:"The exposed-node problem occurs when a device unnecessarily avoids transmitting because it hears another nearby transmission, even though its own transmission would not cause harmful interference.",
395:"Wi-Fi interference comes from other access points, overlapping channels, Bluetooth and other radios, physical obstacles, and electronic noise. It can reduce speed and reliability.",
396:"2.4 GHz generally travels farther and penetrates obstacles better but has fewer crowded channels. 5 GHz usually offers more capacity and less range.",
397:"Channel overlap means neighboring networks use overlapping frequency ranges, causing interference. Choosing suitable non-overlapping channels can improve wireless performance.",
398:"Roaming is the process of moving a wireless client from one access point to another while maintaining network connectivity. Good roaming minimizes interruption.",
399:"WPA2 is a widely deployed Wi-Fi security standard using strong encryption such as AES-CCMP. It replaced weaker earlier Wi-Fi security mechanisms.",
400:"WPA3 is a newer Wi-Fi security standard with stronger authentication and improved protections. It includes modern mechanisms such as SAE for personal networks.",
401:"Wi-Fi authentication controls who can join the network, while encryption protects wireless traffic from being easily read or modified by nearby attackers.",
402:"Check signal strength and interference in the weak area, inspect channel selection, test 2.4/5 GHz behavior, and check access-point placement or roaming.",
403:"A firewall controls network traffic according to security rules. It can filter traffic based on addresses, ports, protocols, connection state, and sometimes application data.",
404:"A stateless firewall evaluates each packet independently. A stateful firewall tracks connection state and can make decisions based on whether traffic belongs to an established session.",
405:"An access control list is an ordered set of allow/deny rules. It can control which traffic or users are permitted to access a resource.",
406:"A security group is a logical set of network traffic rules attached to a resource, commonly in cloud environments. It controls allowed inbound or outbound connections.",
407:"A DMZ is a network segment designed to isolate publicly reachable services from the internal trusted network. It limits the impact of a compromise.",
408:"A denial-of-service attack attempts to make a service unavailable by exhausting bandwidth, processing power, memory, connections, or another resource.",
409:"A distributed denial-of-service attack uses many compromised or coordinated systems to attack a target simultaneously. Distribution makes filtering more difficult.",
410:"IP spoofing means forging the source IP address in packets. It can hide the true sender or bypass weak source-based controls, although return traffic may not reach the attacker.",
411:"ARP spoofing forges local ARP information so victims associate an attacker's MAC with another IP. It can redirect LAN traffic through the attacker.",
412:"DNS spoofing provides false DNS answers so a name resolves to an attacker-controlled or incorrect address. It can redirect users to malicious destinations.",
413:"DNS cache poisoning inserts false DNS data into a resolver's cache. Users can then be directed to incorrect destinations until the bad entry expires or is removed.",
414:"A man-in-the-middle attack secretly positions an attacker between two endpoints. The attacker may read or modify communication while attempting to remain undetected.",
415:"A SYN flood sends many TCP SYN requests without completing connections. It can consume server connection-state resources and prevent legitimate clients from connecting.",
416:"Port scanning probes a host for open or reachable ports. It is used legitimately for inventory and security testing but can also support reconnaissance by attackers.",
417:"A brute-force attack repeatedly tries passwords or credentials against a service. Rate limits, strong authentication, lockouts, and MFA can reduce this risk.",
418:"Network segmentation divides a network into controlled zones. It limits unnecessary communication and helps contain attacks or failures.",
419:"Least privilege means giving users and systems only the access they need. It reduces the damage possible if an account or service is compromised.",
420:"A VPN creates an encrypted or otherwise protected tunnel across an untrusted network. It allows remote or site-to-site communication as if a controlled path existed.",
421:"A site-to-site VPN connects whole networks or gateways. A remote-access VPN connects an individual user's device to a private network.",
422:"Common controls include firewalls, segmentation, secure protocols, MFA, patching, monitoring, rate limiting, backups, IDS/IPS, and strong access policies.",
423:"FTP is the File Transfer Protocol for transferring files. Traditional FTP uses separate control and data connections and does not encrypt traffic by itself.",
424:"SFTP runs file transfer over SSH and provides encrypted authentication and data transfer. It is different from FTP with TLS, often called FTPS.",
425:"SSH provides encrypted remote access and command execution. It is preferred over Telnet because Telnet sends credentials and traffic without strong built-in encryption.",
426:"SMTP is the protocol used to send email between mail systems and from clients to mail submission servers. It handles message transfer rather than mailbox retrieval.",
427:"IMAP is a mail retrieval protocol that keeps messages on the server and synchronizes folders and message state across clients.",
428:"POP3 is a mail retrieval protocol traditionally designed to download messages from a server to a client. It provides less synchronization than IMAP.",
429:"IMAP is better for synchronized access across multiple devices because mail remains server-side. POP3 is simpler and commonly focuses on downloading messages.",
430:"An MX record tells sending mail servers which hosts accept email for a domain. Lower preference values are normally preferred first.",
431:"The sender's mail server looks up the recipient domain's MX record, connects to an appropriate mail server using SMTP, and transfers the message for delivery.",
432:"MIME defines formats for email content and attachments. It lets email messages represent different media types beyond simple plain text.",
433:"An HTTP proxy receives HTTP requests from clients and forwards them to destination servers. It can provide filtering, caching, access control, or logging.",
434:"WebSocket provides a persistent, two-way communication channel between a client and server. It is useful when both sides need to send messages with low delay.",
435:"Choose WebSocket when the application needs frequent, real-time, bidirectional updates such as chat or live collaboration. Ordinary polling is simpler for occasional updates.",
436:"Server-Sent Events provide a persistent HTTP connection where the server can continuously send events to the client. Communication is primarily server-to-client.",
437:"Polling repeatedly asks for updates; long polling holds a request until data is available; SSE streams server-to-client events; WebSocket supports two-way real-time messaging.",
438:"REST is an architectural style for network APIs based around resources, representations, standard HTTP methods, and stateless interactions. It commonly uses JSON over HTTP.",
439:"An API gateway is an entry point for multiple backend services. It can handle routing, authentication, rate limiting, aggregation, and other cross-cutting concerns.",
440:"gRPC is a high-performance RPC framework commonly using HTTP/2 and Protocol Buffers. It supports strongly typed service definitions and efficient binary communication.",
441:"HTTP/2 multiplexes multiple logical streams over one TCP connection. Frames from different streams can be interleaved instead of requiring separate connections.",
442:"JSON is lightweight, human-readable, widely supported, and easy for web clients and servers to parse. It fits naturally with HTTP-based APIs.",
443:"Load balancing distributes incoming requests across multiple servers or service instances. It can improve capacity, availability, and fault tolerance.",
444:"Load balancing prevents one server from becoming a bottleneck and allows traffic to continue when some servers fail. It also makes horizontal scaling practical.",
445:"An L4 load balancer makes decisions using transport information such as IP addresses and ports. It usually does not need to inspect application contents.",
446:"An L7 load balancer understands application protocols such as HTTP. It can route using hostnames, URLs, headers, cookies, or other application-level data.",
447:"L4 is simpler and often faster because it uses connection-level information. L7 offers smarter application-aware routing but requires more processing.",
448:"Round-robin sends successive requests to servers in a rotating order. It is simple but assumes servers have roughly similar capacity and request cost.",
449:"Weighted round-robin gives stronger servers a larger share of requests. For example, a server with twice the weight may receive about twice as much traffic.",
450:"Least-connections sends new traffic to the server currently handling the fewest active connections. It can work well when connection durations vary.",
451:"Health checks test whether backend servers are functioning and ready to receive traffic. Unhealthy servers are temporarily removed from normal load balancing.",
452:"Session persistence, or sticky sessions, keeps a client's requests associated with the same backend server for some period.",
453:"Sticky sessions can create uneven load and reduce failover flexibility. Stateless applications with shared session storage usually scale more cleanly.",
454:"A reverse proxy can terminate TLS, route requests, cache responses, hide backend servers, enforce security policies, and distribute traffic.",
455:"A CDN is a distributed network of edge servers that caches and serves content closer to users. It reduces distance and load on the origin server.",
456:"A CDN reduces latency by serving cached content from an edge location geographically closer to the user. It also reduces repeated origin requests.",
457:"An edge location is a CDN point of presence where content can be cached and served to nearby users. It is positioned close to demand.",
458:"Cache hit ratio is the percentage of requests served from cache rather than fetched from the origin. A higher ratio generally means better cache efficiency.",
459:"On a cache miss, the CDN obtains the content from the origin or upstream cache, stores it according to caching rules, and returns it to the client.",
460:"Cache-Control defines caching behavior, while ETag provides a validator for a specific representation. Clients can use ETag with conditional requests to avoid unnecessary downloads.",
461:"DNS-based load balancing returns different DNS answers for the same name. It can distribute users by geography, policy, or server availability, subject to DNS caching.",
462:"Anycast lets multiple locations advertise the same IP address. Routing normally sends a user toward a nearby or preferred instance, improving global distribution.",
463:"The client resolves DNS, reaches a CDN or edge, and on a miss the request goes toward the load balancer. A backend server processes it and may query the database before replying.",
464:"Ping tests IP reachability and round-trip response time using ICMP or another supported echo mechanism. It does not test every application or port.",
465:"Ping can fail because ICMP is blocked even when applications work. It also does not prove that DNS, HTTP, a specific TCP port, or the application itself is healthy.",
466:"Traceroute/tracert shows the sequence of responding hops toward a destination. It helps identify where delay or routing problems may appear.",
467:"Traceroute sends probes with increasing TTL values. Each router where the TTL expires can return an ICMP Time Exceeded message, revealing that hop.",
468:"nslookup queries DNS and displays name-resolution results. It is useful for checking records, resolver behavior, and whether a hostname maps correctly.",
469:"dig is a detailed DNS diagnostic tool. It can show query type, answer, authority, TTLs, flags, and the responding DNS server.",
470:"curl can test HTTP/HTTPS endpoints and inspect status codes, headers, redirects, timing, and request behavior. It is useful for separating network from application issues.",
471:"netstat can show network connections, listening ports, routing information, and interface statistics depending on the operating system.",
472:"ss is a Linux utility for inspecting sockets, listening services, TCP state, and connection information. It is commonly faster and more modern than netstat.",
473:"tcpdump captures and displays packets from network interfaces. It is useful for inspecting DNS, TCP handshakes, retransmissions, HTTP traffic, and other packet-level behavior.",
474:"Wireshark is a graphical packet-analysis tool. It decodes protocols and lets engineers inspect individual packets, streams, timings, and communication patterns.",
475:"Test the destination IP and port using a tool such as nc, telnet where appropriate, curl for HTTP, or an application-specific client. Then check firewall and listener state.",
476:"Compare access by hostname and by IP, inspect DNS records with nslookup/dig, check resolver settings, and test from another network. If IP works but name fails, DNS is suspect.",
477:"Check the routing table and default gateway, then use traceroute to identify path problems. Compare routes from working and failing hosts.",
478:"Check whether loss occurs locally or at later hops, compare wired and wireless paths, inspect interface errors, and capture packets if needed.",
479:"Measure latency across hops, check congestion and queueing, compare different times and paths, and inspect CPU, Wi-Fi quality, or overloaded links.",
480:"Check DNS resolution, routing, firewall rules, port reachability, server listening state, packet captures, and application logs. A timeout usually means traffic is being dropped or not answered.",
481:"Connection refused usually means the host is reachable but no service is accepting the port, often causing an RST. A timeout usually means packets are being dropped or no response returns.",
482:"Check DNS records and resolver settings, compare nslookup/dig results, inspect hosts-file overrides, and verify that the hostname resolves to the expected address.",
483:"Check the service's listening address and firewall, verify the remote route and port, inspect security-group rules, and test from another host on the same network.",
484:"The browser resolves DNS, establishes network connectivity and usually TCP, performs TLS for HTTPS, sends the HTTP request, receives the response, and fetches additional resources as needed.",
485:"Investigate DNS lookup time, cold TCP/TLS setup, CDN cache misses, connection reuse, server-side connection setup, and slow routes. Compare first and repeated requests.",
486:"Check the path from IP routing through firewall rules and TCP port 443, then inspect the server listener and TLS configuration. DNS is already known to work.",
487:"Possible causes include firewall rules, server backlog/resource limits, asymmetric routing, broken return paths, NAT issues, or a server that cannot complete handshake processing.",
488:"High latency can come from long physical distance, routing, queueing, congestion, retransmissions, or slow protocol handshakes. High bandwidth does not imply low delay.",
489:"For prefix /p, total addresses per subnet are 2^(32-p). Traditional usable hosts are two fewer for normal IPv4 subnets; subnet counts depend on the original prefix.",
490:"Convert both IPs and the mask to integers, compute (ip1 & mask) and (ip2 & mask), and compare the two network values. Equal values mean the same subnet.",
491:"Convert the IP and mask to 32-bit integers, perform bitwise AND, and convert the result back to dotted-decimal notation.",
492:"Convert each octet to 8 bits or compute value = value*256 + octet from left to right. The final result is the 32-bit integer representation.",
493:"Parse the CIDR prefix, convert the address and target to integers, create a mask from the prefix length, and test whether (target & mask) equals (network & mask).",
494:"Store routes as prefix, next hop, and prefix length, then compare the destination against every matching prefix. Choose the match with the greatest prefix length.",
495:"Store DNS records with their expiration time, usually current_time + TTL. On lookup, return a valid cached entry; otherwise remove it and query upstream DNS.",
496:"Add sequence numbers and acknowledgments to UDP messages, keep unacknowledged data in a buffer, use timers for retransmission, and optionally add flow/congestion control.",
497:"A routing table can use a list for a simple implementation or a trie/prefix tree for efficient CIDR matching. Each entry stores prefix, length, and next hop.",
498:"Use ARP or IPv4 neighbor observations to map IPs to MAC addresses and look for one IP associated with different MAC addresses. DHCP/server logs can also help.",
499:"Represent routers as graph vertices and network links as weighted edges. Run a shortest-path algorithm such as Dijkstra to find the minimum-cost route.",
500:"Dijkstra starts from a router, repeatedly selects the closest unvisited node, and relaxes neighboring edges. OSPF uses this SPF calculation to build shortest paths from its topology database."
}

missing = [n for n in range(1,501) if n not in questions or n not in answers]
if missing:
    raise ValueError(f"Missing questions/answers: {missing[:20]}")

# Build a clean study document.
doc = Document()
sec = doc.sections[0]
sec.top_margin = Inches(0.55)
sec.bottom_margin = Inches(0.55)
sec.left_margin = Inches(0.65)
sec.right_margin = Inches(0.65)

styles = doc.styles
styles["Normal"].font.name = "Aptos"
styles["Normal"].font.size = Pt(10.5)

title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Computer Networks — 500 Placement Questions & Answers")
r.bold = True
r.font.size = Pt(20)

sub = doc.add_paragraph()
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = sub.add_run("Intermediate-level answers • Technical Round + Coding/Problem-Solving Preparation")
r.italic = True
r.font.size = Pt(11)

intro = doc.add_paragraph()
intro.add_run("How to use this: ").bold = True
intro.add_run("Try answering each question yourself first, then compare with the short explanation. The wording follows the uploaded question bank and the answers are intentionally kept simple enough for placement revision.")

sections = [
    (1,20,"1. Networking Fundamentals"),
    (21,40,"2. OSI Model"),
    (41,60,"3. TCP/IP Model"),
    (61,80,"4. Physical & Data Link Layer"),
    (81,100,"5. Switching, Ethernet & VLANs"),
    (101,120,"6. IP Addressing & IPv4"),
    (121,140,"7. Subnetting & CIDR"),
    (141,160,"8. IPv6"),
    (161,180,"9. ARP, ICMP & Local Delivery"),
    (181,201,"10. Routing Fundamentals"),
    (202,221,"11. Routing Protocols"),
    (222,241,"12. TCP Fundamentals"),
    (242,261,"13. TCP Flow, Congestion & Connection Management"),
    (262,281,"14. UDP, Ports & Sockets"),
    (282,301,"15. DNS"),
    (302,322,"16. HTTP, HTTPS & Web"),
    (323,342,"17. TLS, Certificates & Security Basics"),
    (343,362,"18. DHCP, NAT & Network Services"),
    (363,382,"19. Network Devices"),
    (383,402,"20. Wireless Networking"),
    (403,422,"21. Network Security & Attacks"),
    (423,442,"22. Application Protocols & Email"),
    (443,463,"23. Load Balancing, CDN & Distributed Networking"),
    (464,483,"24. Troubleshooting & Networking Commands"),
    (484,500,"25. Placement Scenarios, Coding & Rapid-Fire"),
]

for start, end, heading in sections:
    doc.add_page_break()
    h = doc.add_paragraph()
    rr = h.add_run(heading)
    rr.bold = True
    rr.font.size = Pt(15)
    for n in range(start, end + 1):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(1)
        qrun = p.add_run(f"{n}. {questions[n]}")
        qrun.bold = True
        qrun.font.size = Pt(10.5)
        a = doc.add_paragraph()
        a.paragraph_format.left_indent = Inches(0.18)
        a.paragraph_format.space_after = Pt(6)
        ar = a.add_run("Answer: " + answers[n])
        ar.font.size = Pt(10)

# Change this line at the bottom of your script:
out = Path.home() / "Desktop" / "holigun.docx"
doc.save(out)

print(f"Created: {out}")
print(f"Questions included: {len(questions)}")
print("All 500 questions have concise intermediate-level answers.")
